In [ ]:
import pandas as pd
import plotly.express as px
from google.colab import files

In [8]:
from google.colab import files
uploaded = files.upload()

Saving IPL.csv to IPL.csv

In [9]:
import pandas as pd
df=pd.read_csv("IPL.csv")
df.head()

/tmp/ipykernel_5647/3501953531.py:2: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("IPL.csv")

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [ ]:
df.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter',
       'power_surge_start', 'batter_runs', 'batter_balls', 'bowler_wicket',
       'batting_partners', 'next_batter', 'striker_out'],
      dtype='object')

In [ ]:
df.shape
df.head(10)

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False
5,141612,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,...,5,0,NaN,NaN,0,4,0,"('BB McCullum', 'SC Ganguly')",NaN,False
6,141613,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,...,6,0,NaN,NaN,0,5,0,"('BB McCullum', 'SC Ganguly')",NaN,False
7,141614,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,...,7,0,NaN,NaN,0,6,0,"('BB McCullum', 'SC Ganguly')",NaN,False
8,141615,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,...,8,0,NaN,NaN,4,7,0,"('BB McCullum', 'SC Ganguly')",NaN,False
9,141616,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,...,9,0,NaN,NaN,8,8,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [ ]:
missing_values=df.isnull().sum()
missing_values[missing_values>0]

extra_type           268185
wicket_kind          269572
player_out           269572
fielders             273433
runs_target          147168
review_batter        282771
team_reviewed        282771
review_decision      282771
umpire               282771
win_outcome            4724
superover_winner     279782
result_type          278954
method               279788
new_batter           270085
power_surge_start    283678
next_batter          270085
dtype: int64

In [ ]:
df.describe()

,Unnamed: 0,match_id,innings,over,ball,ball_no,bat_pos,runs_batter,balls_faced,valid_ball,...,year,balls_per_over,overs,team_runs,team_balls,team_wicket,power_surge_start,batter_runs,batter_balls,bowler_wicket
count,283678.000000,2.836780e+05,283678.000000,283678.000000,283678.000000,283678.000000,283678.000000,283678.000000,283678.000000,283678.000000,...,283678.000000,283678.0,283678.0,283678.000000,283678.000000,283678.000000,0.0,283678.000000,283678.000000,283678.000000
mean,141838.500000,9.535684e+05,1.482787,9.190833,3.488847,9.539717,3.616445,1.281421,0.967082,0.962912,...,2016.889406,6.0,20.0,77.423099,58.596328,2.460624,NaN,18.376621,13.993813,0.045530
std,81890.929169,3.865091e+05,0.502511,5.680845,1.708286,5.682271,2.170569,1.655126,0.178421,0.188977,...,5.352468,0.0,0.0,50.167985,34.113517,2.102515,NaN,18.607095,11.815576,0.208465
min,0.000000,3.359820e+05,1.000000,0.000000,1.000000,0.100000,1.000000,0.000000,0.000000,0.000000,...,2008.000000,6.0,20.0,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000
25%,70919.250000,5.483590e+05,1.000000,4.000000,2.000000,4.500000,2.000000,0.000000,1.000000,1.000000,...,2012.000000,6.0,20.0,36.000000,29.000000,1.000000,NaN,4.000000,5.000000,0.000000
50%,141838.500000,1.082612e+06,1.000000,9.000000,3.000000,9.400000,3.000000,1.000000,1.000000,1.000000,...,2017.000000,6.0,20.0,73.000000,58.000000,2.000000,NaN,12.000000,11.000000,0.000000
75%,212757.750000,1.304066e+06,2.000000,14.000000,5.000000,14.400000,5.000000,1.000000,1.000000,1.000000,...,2022.000000,6.0,20.0,114.000000,88.000000,4.000000,NaN,27.000000,20.000000,0.000000
max,283677.000000,1.529267e+06,6.000000,19.000000,7.000000,19.600000,11.000000,6.000000,1.000000,1.000000,...,2026.000000,6.0,20.0,287.000000,121.000000,10.000000,NaN,175.000000,73.000000,1.000000

In [ ]:
import plotly.express as px

top_batters = (
    df.groupby("batter")["runs_batter"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

fig = px.bar(
    top_batters,
    x="batter",
    y="runs_batter",
    title="Top 10 IPL Run Scorers"
)

fig.show()

In [ ]:
import plotly.express as px

top_bowlers = (
    df.groupby("bowler")["bowler_wicket"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

fig = px.bar(
    top_bowlers,
    x="bowler",
    y="bowler_wicket",
    title="Top 10 IPL Wicket Takers"
)

fig.show()

In [ ]:
season_matches = (
    df.groupby("season")["match_id"]
    .nunique()
    .reset_index()
)

fig = px.line(
    season_matches,
    x="season",
    y="match_id",
    title="Matches Played Per Season",
    markers=True
)

fig.show()

In [ ]:
team_wins = (
    df[['match_id', 'match_won_by']]
    .drop_duplicates()
    .groupby('match_won_by')
    .size()
    .reset_index(name='wins')
    .sort_values('wins', ascending=False)
    .head(10)
)

fig = px.pie(
    team_wins,
    names='match_won_by',
    values='wins',
    title='Top Winning Teams'
)

fig.show()